// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: trove/v1/module.proto

package troverpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreServices_Emit_FullMethodName                   = "/trove.v1.CoreServices/Emit"
	CoreServices_BlobPut_FullMethodName                = "/trove.v1.CoreServices/BlobPut"
	CoreServices_GetEvent_FullMethodName               = "/trove.v1.CoreServices/GetEvent"
	CoreServices_SearchEvents_FullMethodName           = "/trove.v1.CoreServices/SearchEvents"
	CoreServices_GetEventsByType_FullMethodName        = "/trove.v1.CoreServices/GetEventsByType"
	CoreServices_SummarizeRange_FullMethodName         = "/trove.v1.CoreServices/SummarizeRange"
	CoreServices_ListMCPTools_FullMethodName           = "/trove.v1.CoreServices/ListMCPTools"
	CoreServices_CallMCPTool_FullMethodName            = "/trove.v1.CoreServices/CallMCPTool"
	CoreServices_ListTypes_FullMethodName              = "/trove.v1.CoreServices/ListTypes"
	CoreServices_GetType_FullMethodName                = "/trove.v1.CoreServices/GetType"
	CoreServices_ExportType_FullMethodName             = "/trove.v1.CoreServices/ExportType"
	CoreServices_ValidateTypeDefinition_FullMethodName = "/trove.v1.CoreServices/ValidateTypeDefinition"
)

// CoreServicesClient is the client API for CoreServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreServices is implemented by the Trove parent process. Modules reach it
// through trovemodule.Core; see RunRequest.services_broker_id for the internal
// plugin wire format.
type CoreServicesClient interface {
	Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error)
	BlobPut(ctx context.Context, in *BlobPutRequest, opts ...grpc.CallOption) (*BlobPutResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error)
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	GetEventsByType(ctx context.Context, in *GetEventsByTypeRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	SummarizeRange(ctx context.Context, in *SummarizeRangeRequest, opts ...grpc.CallOption) (*Summary, error)
	ListMCPTools(ctx context.Context, in *ListMCPToolsRequest, opts ...grpc.CallOption) (*ListMCPToolsResponse, error)
	CallMCPTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error)
	ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*ListTypesResponse, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error)
	ExportType(ctx context.Context, in *ExportTypeRequest, opts ...grpc.CallOption) (*ExportTypeResponse, error)
	ValidateTypeDefinition(ctx context.Context, in *ValidateTypeDefinitionRequest, opts ...grpc.CallOption) (*ValidateTypeDefinitionResponse, error)
}

type coreServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServicesClient(cc grpc.ClientConnInterface) CoreServicesClient {
	return &coreServicesClient{cc}
}

func (c *coreServicesClient) Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, CoreServices_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) BlobPut(ctx context.Context, in *BlobPutRequest, opts ...grpc.CallOption) (*BlobPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobPutResponse)
	err := c.cc.Invoke(ctx, CoreServices_BlobPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Event)
	err := c.cc.Invoke(ctx, CoreServices_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, CoreServices_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) GetEventsByType(ctx context.Context, in *GetEventsByTypeRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, CoreServices_GetEventsByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) SummarizeRange(ctx context.Context, in *SummarizeRangeRequest, opts ...grpc.CallOption) (*Summary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Summary)
	err := c.cc.Invoke(ctx, CoreServices_SummarizeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) ListMCPTools(ctx context.Context, in *ListMCPToolsRequest, opts ...grpc.CallOption) (*ListMCPToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMCPToolsResponse)
	err := c.cc.Invoke(ctx, CoreServices_ListMCPTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) CallMCPTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPToolCallResponse)
	err := c.cc.Invoke(ctx, CoreServices_CallMCPTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*ListTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTypesResponse)
	err := c.cc.Invoke(ctx, CoreServices_ListTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTypeResponse)
	err := c.cc.Invoke(ctx, CoreServices_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) ExportType(ctx context.Context, in *ExportTypeRequest, opts ...grpc.CallOption) (*ExportTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportTypeResponse)
	err := c.cc.Invoke(ctx, CoreServices_ExportType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) ValidateTypeDefinition(ctx context.Context, in *ValidateTypeDefinitionRequest, opts ...grpc.CallOption) (*ValidateTypeDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTypeDefinitionResponse)
	err := c.cc.Invoke(ctx, CoreServices_ValidateTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServicesServer is the server API for CoreServices service.
// All implementations must embed UnimplementedCoreServicesServer
// for forward compatibility.
//
// CoreServices is implemented by the Trove parent process. Modules reach it
// through trovemodule.Core; see RunRequest.services_broker_id for the internal
// plugin wire format.
type CoreServicesServer interface {
	Emit(context.Context, *Event) (*EmitResponse, error)
	BlobPut(context.Context, *BlobPutRequest) (*BlobPutResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*Event, error)
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	GetEventsByType(context.Context, *GetEventsByTypeRequest) (*SearchEventsResponse, error)
	SummarizeRange(context.Context, *SummarizeRangeRequest) (*Summary, error)
	ListMCPTools(context.Context, *ListMCPToolsRequest) (*ListMCPToolsResponse, error)
	CallMCPTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error)
	ListTypes(context.Context, *ListTypesRequest) (*ListTypesResponse, error)
	GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error)
	ExportType(context.Context, *ExportTypeRequest) (*ExportTypeResponse, error)
	ValidateTypeDefinition(context.Context, *ValidateTypeDefinitionRequest) (*ValidateTypeDefinitionResponse, error)
	mustEmbedUnimplementedCoreServicesServer()
}

// UnimplementedCoreServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServicesServer struct{}

func (UnimplementedCoreServicesServer) Emit(context.Context, *Event) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedCoreServicesServer) BlobPut(context.Context, *BlobPutRequest) (*BlobPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlobPut not implemented")
}
func (UnimplementedCoreServicesServer) GetEvent(context.Context, *GetEventRequest) (*Event, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedCoreServicesServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedCoreServicesServer) GetEventsByType(context.Context, *GetEventsByTypeRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByType not implemented")
}
func (UnimplementedCoreServicesServer) SummarizeRange(context.Context, *SummarizeRangeRequest) (*Summary, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeRange not implemented")
}
func (UnimplementedCoreServicesServer) ListMCPTools(context.Context, *ListMCPToolsRequest) (*ListMCPToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMCPTools not implemented")
}
func (UnimplementedCoreServicesServer) CallMCPTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallMCPTool not implemented")
}
func (UnimplementedCoreServicesServer) ListTypes(context.Context, *ListTypesRequest) (*ListTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTypes not implemented")
}
func (UnimplementedCoreServicesServer) GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedCoreServicesServer) ExportType(context.Context, *ExportTypeRequest) (*ExportTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportType not implemented")
}
func (UnimplementedCoreServicesServer) ValidateTypeDefinition(context.Context, *ValidateTypeDefinitionRequest) (*ValidateTypeDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateTypeDefinition not implemented")
}
func (UnimplementedCoreServicesServer) mustEmbedUnimplementedCoreServicesServer() {}
func (UnimplementedCoreServicesServer) testEmbeddedByValue()                      {}

// UnsafeCoreServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServicesServer will
// result in compilation errors.
type UnsafeCoreServicesServer interface {
	mustEmbedUnimplementedCoreServicesServer()
}

func RegisterCoreServicesServer(s grpc.ServiceRegistrar, srv CoreServicesServer) {
	// If the following call panics, it indicates UnimplementedCoreServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreServices_ServiceDesc, srv)
}

func _CoreServices_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).Emit(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_BlobPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).BlobPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_BlobPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).BlobPut(ctx, req.(*BlobPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_GetEventsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).GetEventsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_GetEventsByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).GetEventsByType(ctx, req.(*GetEventsByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_SummarizeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).SummarizeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_SummarizeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).SummarizeRange(ctx, req.(*SummarizeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_ListMCPTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMCPToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).ListMCPTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_ListMCPTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).ListMCPTools(ctx, req.(*ListMCPToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_CallMCPTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).CallMCPTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_CallMCPTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).CallMCPTool(ctx, req.(*MCPToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_ListTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).ListTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_ListTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).ListTypes(ctx, req.(*ListTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_ExportType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).ExportType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_ExportType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).ExportType(ctx, req.(*ExportTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_ValidateTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).ValidateTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_ValidateTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).ValidateTypeDefinition(ctx, req.(*ValidateTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreServices_ServiceDesc is the grpc.ServiceDesc for CoreServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.CoreServices",
	HandlerType: (*CoreServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _CoreServices_Emit_Handler,
		},
		{
			MethodName: "BlobPut",
			Handler:    _CoreServices_BlobPut_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _CoreServices_GetEvent_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _CoreServices_SearchEvents_Handler,
		},
		{
			MethodName: "GetEventsByType",
			Handler:    _CoreServices_GetEventsByType_Handler,
		},
		{
			MethodName: "SummarizeRange",
			Handler:    _CoreServices_SummarizeRange_Handler,
		},
		{
			MethodName: "ListMCPTools",
			Handler:    _CoreServices_ListMCPTools_Handler,
		},
		{
			MethodName: "CallMCPTool",
			Handler:    _CoreServices_CallMCPTool_Handler,
		},
		{
			MethodName: "ListTypes",
			Handler:    _CoreServices_ListTypes_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _CoreServices_GetType_Handler,
		},
		{
			MethodName: "ExportType",
			Handler:    _CoreServices_ExportType_Handler,
		},
		{
			MethodName: "ValidateTypeDefinition",
			Handler:    _CoreServices_ValidateTypeDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	HTTPModule_HandleHTTP_FullMethodName = "/trove.v1.HTTPModule/HandleHTTP"
)

// HTTPModuleClient is the client API for HTTPModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTPModule is implemented by modules that handle HTTP routes via the gateway.
type HTTPModuleClient interface {
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type hTTPModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPModuleClient(cc grpc.ClientConnInterface) HTTPModuleClient {
	return &hTTPModuleClient{cc}
}

func (c *hTTPModuleClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, HTTPModule_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPModuleServer is the server API for HTTPModule service.
// All implementations must embed UnimplementedHTTPModuleServer
// for forward compatibility.
//
// HTTPModule is implemented by modules that handle HTTP routes via the gateway.
type HTTPModuleServer interface {
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	mustEmbedUnimplementedHTTPModuleServer()
}

// UnimplementedHTTPModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPModuleServer struct{}

func (UnimplementedHTTPModuleServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedHTTPModuleServer) mustEmbedUnimplementedHTTPModuleServer() {}
func (UnimplementedHTTPModuleServer) testEmbeddedByValue()                    {}

// UnsafeHTTPModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPModuleServer will
// result in compilation errors.
type UnsafeHTTPModuleServer interface {
	mustEmbedUnimplementedHTTPModuleServer()
}

func RegisterHTTPModuleServer(s grpc.ServiceRegistrar, srv HTTPModuleServer) {
	// If the following call panics, it indicates UnimplementedHTTPModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPModule_ServiceDesc, srv)
}

func _HTTPModule_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPModuleServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPModule_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPModuleServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPModule_ServiceDesc is the grpc.ServiceDesc for HTTPModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.HTTPModule",
	HandlerType: (*HTTPModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHTTP",
			Handler:    _HTTPModule_HandleHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	AuthModule_ValidateAuth_FullMethodName = "/trove.v1.AuthModule/ValidateAuth"
)

// AuthModuleClient is the client API for AuthModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthModule is implemented by modules that validate gateway requests.
type AuthModuleClient interface {
	ValidateAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthModuleClient(cc grpc.ClientConnInterface) AuthModuleClient {
	return &authModuleClient{cc}
}

func (c *authModuleClient) ValidateAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthModule_ValidateAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthModuleServer is the server API for AuthModule service.
// All implementations must embed UnimplementedAuthModuleServer
// for forward compatibility.
//
// AuthModule is implemented by modules that validate gateway requests.
type AuthModuleServer interface {
	ValidateAuth(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAuthModuleServer()
}

// UnimplementedAuthModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthModuleServer struct{}

func (UnimplementedAuthModuleServer) ValidateAuth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAuth not implemented")
}
func (UnimplementedAuthModuleServer) mustEmbedUnimplementedAuthModuleServer() {}
func (UnimplementedAuthModuleServer) testEmbeddedByValue()                    {}

// UnsafeAuthModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthModuleServer will
// result in compilation errors.
type UnsafeAuthModuleServer interface {
	mustEmbedUnimplementedAuthModuleServer()
}

func RegisterAuthModuleServer(s grpc.ServiceRegistrar, srv AuthModuleServer) {
	// If the following call panics, it indicates UnimplementedAuthModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthModule_ServiceDesc, srv)
}

func _AuthModule_ValidateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthModuleServer).ValidateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthModule_ValidateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthModuleServer).ValidateAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthModule_ServiceDesc is the grpc.ServiceDesc for AuthModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.AuthModule",
	HandlerType: (*AuthModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAuth",
			Handler:    _AuthModule_ValidateAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	MCPModule_CallTool_FullMethodName = "/trove.v1.MCPModule/CallTool"
)

// MCPModuleClient is the client API for MCPModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPModule is implemented by modules that provide MCP tools.
type MCPModuleClient interface {
	CallTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error)
}

type mCPModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPModuleClient(cc grpc.ClientConnInterface) MCPModuleClient {
	return &mCPModuleClient{cc}
}

func (c *mCPModuleClient) CallTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPToolCallResponse)
	err := c.cc.Invoke(ctx, MCPModule_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPModuleServer is the server API for MCPModule service.
// All implementations must embed UnimplementedMCPModuleServer
// for forward compatibility.
//
// MCPModule is implemented by modules that provide MCP tools.
type MCPModuleServer interface {
	CallTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error)
	mustEmbedUnimplementedMCPModuleServer()
}

// UnimplementedMCPModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPModuleServer struct{}

func (UnimplementedMCPModuleServer) CallTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMCPModuleServer) mustEmbedUnimplementedMCPModuleServer() {}
func (UnimplementedMCPModuleServer) testEmbeddedByValue()                   {}

// UnsafeMCPModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPModuleServer will
// result in compilation errors.
type UnsafeMCPModuleServer interface {
	mustEmbedUnimplementedMCPModuleServer()
}

func RegisterMCPModuleServer(s grpc.ServiceRegistrar, srv MCPModuleServer) {
	// If the following call panics, it indicates UnimplementedMCPModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPModule_ServiceDesc, srv)
}

func _MCPModule_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPModuleServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPModule_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPModuleServer).CallTool(ctx, req.(*MCPToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPModule_ServiceDesc is the grpc.ServiceDesc for MCPModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.MCPModule",
	HandlerType: (*MCPModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTool",
			Handler:    _MCPModule_CallTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	SourceModule_Run_FullMethodName         = "/trove.v1.SourceModule/Run"
	SourceModule_Healthcheck_FullMethodName = "/trove.v1.SourceModule/Healthcheck"
)

// SourceModuleClient is the client API for SourceModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type sourceModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceModuleClient(cc grpc.ClientConnInterface) SourceModuleClient {
	return &sourceModuleClient{cc}
}

func (c *sourceModuleClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, SourceModule_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceModuleClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, SourceModule_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceModuleServer is the server API for SourceModule service.
// All implementations must embed UnimplementedSourceModuleServer
// for forward compatibility.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	mustEmbedUnimplementedSourceModuleServer()
}

// UnimplementedSourceModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceModuleServer struct{}

func (UnimplementedSourceModuleServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedSourceModuleServer) Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedSourceModuleServer) mustEmbedUnimplementedSourceModuleServer() {}
func (UnimplementedSourceModuleServer) testEmbeddedByValue()                      {}

// UnsafeSourceModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceModuleServer will
// result in compilation errors.
type UnsafeSourceModuleServer interface {
	mustEmbedUnimplementedSourceModuleServer()
}

func RegisterSourceModuleServer(s grpc.ServiceRegistrar, srv SourceModuleServer) {
	// If the following call panics, it indicates UnimplementedSourceModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceModule_ServiceDesc, srv)
}

func _SourceModule_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceModuleServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceModule_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceModuleServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceModule_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceModuleServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceModule_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceModuleServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceModule_ServiceDesc is the grpc.ServiceDesc for SourceModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.SourceModule",
	HandlerType: (*SourceModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _SourceModule_Run_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _SourceModule_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	ProcessorModule_Process_FullMethodName     = "/trove.v1.ProcessorModule/Process"
	ProcessorModule_Healthcheck_FullMethodName = "/trove.v1.ProcessorModule/Healthcheck"
)

// ProcessorModuleClient is the client API for ProcessorModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProcessorModule is implemented by event-routing processor modules.
type ProcessorModuleClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type processorModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorModuleClient(cc grpc.ClientConnInterface) ProcessorModuleClient {
	return &processorModuleClient{cc}
}

func (c *processorModuleClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, ProcessorModule_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorModuleClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, ProcessorModule_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessorModuleServer is the server API for ProcessorModule service.
// All implementations must embed UnimplementedProcessorModuleServer
// for forward compatibility.
//
// ProcessorModule is implemented by event-routing processor modules.
type ProcessorModuleServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	mustEmbedUnimplementedProcessorModuleServer()
}

// UnimplementedProcessorModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessorModuleServer struct{}

func (UnimplementedProcessorModuleServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedProcessorModuleServer) Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedProcessorModuleServer) mustEmbedUnimplementedProcessorModuleServer() {}
func (UnimplementedProcessorModuleServer) testEmbeddedByValue()                         {}

// UnsafeProcessorModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessorModuleServer will
// result in compilation errors.
type UnsafeProcessorModuleServer interface {
	mustEmbedUnimplementedProcessorModuleServer()
}

func RegisterProcessorModuleServer(s grpc.ServiceRegistrar, srv ProcessorModuleServer) {
	// If the following call panics, it indicates UnimplementedProcessorModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessorModule_ServiceDesc, srv)
}

func _ProcessorModule_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorModuleServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessorModule_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorModuleServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessorModule_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorModuleServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessorModule_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorModuleServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessorModule_ServiceDesc is the grpc.ServiceDesc for ProcessorModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessorModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.ProcessorModule",
	HandlerType: (*ProcessorModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _ProcessorModule_Process_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _ProcessorModule_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	SinkModule_Handle_FullMethodName      = "/trove.v1.SinkModule/Handle"
	SinkModule_Healthcheck_FullMethodName = "/trove.v1.SinkModule/Healthcheck"
)

// SinkModuleClient is the client API for SinkModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SinkModule is implemented by event-routing sink modules.
type SinkModuleClient interface {
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type sinkModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewSinkModuleClient(cc grpc.ClientConnInterface) SinkModuleClient {
	return &sinkModuleClient{cc}
}

func (c *sinkModuleClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, SinkModule_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkModuleClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, SinkModule_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinkModuleServer is the server API for SinkModule service.
// All implementations must embed UnimplementedSinkModuleServer
// for forward compatibility.
//
// SinkModule is implemented by event-routing sink modules.
type SinkModuleServer interface {
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	mustEmbedUnimplementedSinkModuleServer()
}

// UnimplementedSinkModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSinkModuleServer struct{}

func (UnimplementedSinkModuleServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedSinkModuleServer) Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedSinkModuleServer) mustEmbedUnimplementedSinkModuleServer() {}
func (UnimplementedSinkModuleServer) testEmbeddedByValue()                    {}

// UnsafeSinkModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SinkModuleServer will
// result in compilation errors.
type UnsafeSinkModuleServer interface {
	mustEmbedUnimplementedSinkModuleServer()
}

func RegisterSinkModuleServer(s grpc.ServiceRegistrar, srv SinkModuleServer) {
	// If the following call panics, it indicates UnimplementedSinkModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SinkModule_ServiceDesc, srv)
}

func _SinkModule_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkModuleServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkModule_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkModuleServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkModule_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkModuleServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkModule_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkModuleServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SinkModule_ServiceDesc is the grpc.ServiceDesc for SinkModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SinkModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.SinkModule",
	HandlerType: (*SinkModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _SinkModule_Handle_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _SinkModule_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}
