// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trove/v1/module.proto

package troverpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Revision mirrors journal.Revision for RPC transport.
type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"` // RFC3339
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON
	BlobRef       string                 `protobuf:"bytes,6,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	SchemaRef     string                 `protobuf:"bytes,7,opt,name=schema_ref,json=schemaRef,proto3" json:"schema_ref,omitempty"`
	Operation     string                 `protobuf:"bytes,8,opt,name=operation,proto3" json:"operation,omitempty"`
	RecordRef     string                 `protobuf:"bytes,9,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Transforms    []byte                 `protobuf:"bytes,10,opt,name=transforms,proto3" json:"transforms,omitempty"` // JSON Patch array
	Producer      string                 `protobuf:"bytes,11,opt,name=producer,proto3" json:"producer,omitempty"`     // host-stamped module identity; read-only for modules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_trove_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *Revision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Revision) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Revision) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Revision) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Revision) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Revision) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

func (x *Revision) GetSchemaRef() string {
	if x != nil {
		return x.SchemaRef
	}
	return ""
}

func (x *Revision) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Revision) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *Revision) GetTransforms() []byte {
	if x != nil {
		return x.Transforms
	}
	return nil
}

func (x *Revision) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

type AppendRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	RecordRef     string                 `protobuf:"bytes,2,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"` // RFC3339
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Transforms    []byte                 `protobuf:"bytes,7,opt,name=transforms,proto3" json:"transforms,omitempty"`
	BlobRef       string                 `protobuf:"bytes,8,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRevisionRequest) Reset() {
	*x = AppendRevisionRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRevisionRequest) ProtoMessage() {}

func (x *AppendRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRevisionRequest.ProtoReflect.Descriptor instead.
func (*AppendRevisionRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{1}
}

func (x *AppendRevisionRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AppendRevisionRequest) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *AppendRevisionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppendRevisionRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AppendRevisionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AppendRevisionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendRevisionRequest) GetTransforms() []byte {
	if x != nil {
		return x.Transforms
	}
	return nil
}

func (x *AppendRevisionRequest) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

type AppendRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevisionId    string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	RecordRef     string                 `protobuf:"bytes,2,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Completeness  string                 `protobuf:"bytes,4,opt,name=completeness,proto3" json:"completeness,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRevisionResponse) Reset() {
	*x = AppendRevisionResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRevisionResponse) ProtoMessage() {}

func (x *AppendRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRevisionResponse.ProtoReflect.Descriptor instead.
func (*AppendRevisionResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRevisionResponse) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *AppendRevisionResponse) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *AppendRevisionResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendRevisionResponse) GetCompleteness() string {
	if x != nil {
		return x.Completeness
	}
	return ""
}

func (x *AppendRevisionResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type BlobPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutRequest) Reset() {
	*x = BlobPutRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutRequest) ProtoMessage() {}

func (x *BlobPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutRequest.ProtoReflect.Descriptor instead.
func (*BlobPutRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{3}
}

func (x *BlobPutRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlobPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobRef       string                 `protobuf:"bytes,1,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutResponse) Reset() {
	*x = BlobPutResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutResponse) ProtoMessage() {}

func (x *BlobPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutResponse.ProtoReflect.Descriptor instead.
func (*BlobPutResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{4}
}

func (x *BlobPutResponse) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

type GetRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionRequest) Reset() {
	*x = GetRevisionRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionRequest) ProtoMessage() {}

func (x *GetRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetRevisionRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *GetRevisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TypePrefix    string                 `protobuf:"bytes,2,opt,name=type_prefix,json=typePrefix,proto3" json:"type_prefix,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	TimeFrom      string                 `protobuf:"bytes,4,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"` // optional RFC3339
	TimeTo        string                 `protobuf:"bytes,5,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`       // optional RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRevisionsRequest) Reset() {
	*x = SearchRevisionsRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRevisionsRequest) ProtoMessage() {}

func (x *SearchRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRevisionsRequest.ProtoReflect.Descriptor instead.
func (*SearchRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRevisionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRevisionsRequest) GetTypePrefix() string {
	if x != nil {
		return x.TypePrefix
	}
	return ""
}

func (x *SearchRevisionsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchRevisionsRequest) GetTimeFrom() string {
	if x != nil {
		return x.TimeFrom
	}
	return ""
}

func (x *SearchRevisionsRequest) GetTimeTo() string {
	if x != nil {
		return x.TimeTo
	}
	return ""
}

type SearchRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*Revision            `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRevisionsResponse) Reset() {
	*x = SearchRevisionsResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRevisionsResponse) ProtoMessage() {}

func (x *SearchRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRevisionsResponse.ProtoReflect.Descriptor instead.
func (*SearchRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRevisionsResponse) GetRevisions() []*Revision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type GetRevisionsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TimeFrom      string                 `protobuf:"bytes,2,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"` // optional RFC3339
	TimeTo        string                 `protobuf:"bytes,3,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`       // optional RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionsByTypeRequest) Reset() {
	*x = GetRevisionsByTypeRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionsByTypeRequest) ProtoMessage() {}

func (x *GetRevisionsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionsByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetRevisionsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{8}
}

func (x *GetRevisionsByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetRevisionsByTypeRequest) GetTimeFrom() string {
	if x != nil {
		return x.TimeFrom
	}
	return ""
}

func (x *GetRevisionsByTypeRequest) GetTimeTo() string {
	if x != nil {
		return x.TimeTo
	}
	return ""
}

// Record mirrors the folded record_heads projection for RPC transport.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordRef     string                 `protobuf:"bytes,1,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Completeness  string                 `protobuf:"bytes,3,opt,name=completeness,proto3" json:"completeness,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"` // JSON
	ContentRef    string                 `protobuf:"bytes,7,opt,name=content_ref,json=contentRef,proto3" json:"content_ref,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_trove_v1_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{9}
}

func (x *Record) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *Record) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Record) GetCompleteness() string {
	if x != nil {
		return x.Completeness
	}
	return ""
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Record) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Record) GetContentRef() string {
	if x != nil {
		return x.ContentRef
	}
	return ""
}

func (x *Record) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordRef     string                 `protobuf:"bytes,1,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // optional; 0 returns latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecordRequest) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *GetRecordRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SearchRecordsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TypePrefix     string                 `protobuf:"bytes,2,opt,name=type_prefix,json=typePrefix,proto3" json:"type_prefix,omitempty"`
	Source         string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	TimeFrom       string                 `protobuf:"bytes,4,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"` // optional RFC3339
	TimeTo         string                 `protobuf:"bytes,5,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`       // optional RFC3339
	IncludeDeleted bool                   `protobuf:"varint,6,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRecordsRequest) Reset() {
	*x = SearchRecordsRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecordsRequest) ProtoMessage() {}

func (x *SearchRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecordsRequest.ProtoReflect.Descriptor instead.
func (*SearchRecordsRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRecordsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRecordsRequest) GetTypePrefix() string {
	if x != nil {
		return x.TypePrefix
	}
	return ""
}

func (x *SearchRecordsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchRecordsRequest) GetTimeFrom() string {
	if x != nil {
		return x.TimeFrom
	}
	return ""
}

func (x *SearchRecordsRequest) GetTimeTo() string {
	if x != nil {
		return x.TimeTo
	}
	return ""
}

func (x *SearchRecordsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type SearchRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRecordsResponse) Reset() {
	*x = SearchRecordsResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecordsResponse) ProtoMessage() {}

func (x *SearchRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecordsResponse.ProtoReflect.Descriptor instead.
func (*SearchRecordsResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type ListIncompleteRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncompleteRecordsRequest) Reset() {
	*x = ListIncompleteRecordsRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncompleteRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncompleteRecordsRequest) ProtoMessage() {}

func (x *ListIncompleteRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncompleteRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListIncompleteRecordsRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{13}
}

func (x *ListIncompleteRecordsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListIncompleteRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListIncompleteRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncompleteRecordsResponse) Reset() {
	*x = ListIncompleteRecordsResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncompleteRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncompleteRecordsResponse) ProtoMessage() {}

func (x *ListIncompleteRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncompleteRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListIncompleteRecordsResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{14}
}

func (x *ListIncompleteRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type SummarizeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeFrom      string                 `protobuf:"bytes,1,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"` // RFC3339
	TimeTo        string                 `protobuf:"bytes,2,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`       // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRangeRequest) Reset() {
	*x = SummarizeRangeRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRangeRequest) ProtoMessage() {}

func (x *SummarizeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRangeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRangeRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{15}
}

func (x *SummarizeRangeRequest) GetTimeFrom() string {
	if x != nil {
		return x.TimeFrom
	}
	return ""
}

func (x *SummarizeRangeRequest) GetTimeTo() string {
	if x != nil {
		return x.TimeTo
	}
	return ""
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeFrom      string                 `protobuf:"bytes,1,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo        string                 `protobuf:"bytes,2,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	ByType        map[string]int32       `protobuf:"bytes,4,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Notable       []*Revision            `protobuf:"bytes,5,rep,name=notable,proto3" json:"notable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_trove_v1_module_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{16}
}

func (x *Summary) GetTimeFrom() string {
	if x != nil {
		return x.TimeFrom
	}
	return ""
}

func (x *Summary) GetTimeTo() string {
	if x != nil {
		return x.TimeTo
	}
	return ""
}

func (x *Summary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetByType() map[string]int32 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *Summary) GetNotable() []*Revision {
	if x != nil {
		return x.Notable
	}
	return nil
}

type HTTPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MatchedPattern string                 `protobuf:"bytes,3,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	PathValues     map[string]string      `protobuf:"bytes,4,rep,name=path_values,json=pathValues,proto3" json:"path_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers        map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{17}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *HTTPRequest) GetPathValues() map[string]string {
	if x != nil {
		return x.PathValues
	}
	return nil
}

func (x *HTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{18}
}

func (x *HTTPResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type AuthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorId    string                 `protobuf:"bytes,1,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	MatchedPattern string                 `protobuf:"bytes,4,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	PathValues     map[string]string      `protobuf:"bytes,5,rep,name=path_values,json=pathValues,proto3" json:"path_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers        map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RouteModule    string                 `protobuf:"bytes,7,opt,name=route_module,json=routeModule,proto3" json:"route_module,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{19}
}

func (x *AuthRequest) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *AuthRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuthRequest) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *AuthRequest) GetPathValues() map[string]string {
	if x != nil {
		return x.PathValues
	}
	return nil
}

func (x *AuthRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AuthRequest) GetRouteModule() string {
	if x != nil {
		return x.RouteModule
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{20}
}

func (x *AuthResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type MCPToolDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPToolDescriptor) Reset() {
	*x = MCPToolDescriptor{}
	mi := &file_trove_v1_module_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPToolDescriptor) ProtoMessage() {}

func (x *MCPToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPToolDescriptor.ProtoReflect.Descriptor instead.
func (*MCPToolDescriptor) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{21}
}

func (x *MCPToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPToolDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPToolDescriptor) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ListMCPToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPToolsRequest) Reset() {
	*x = ListMCPToolsRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPToolsRequest) ProtoMessage() {}

func (x *ListMCPToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPToolsRequest.ProtoReflect.Descriptor instead.
func (*ListMCPToolsRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{22}
}

type ListMCPToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*MCPToolDescriptor   `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPToolsResponse) Reset() {
	*x = ListMCPToolsResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPToolsResponse) ProtoMessage() {}

func (x *ListMCPToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPToolsResponse.ProtoReflect.Descriptor instead.
func (*ListMCPToolsResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{23}
}

func (x *ListMCPToolsResponse) GetTools() []*MCPToolDescriptor {
	if x != nil {
		return x.Tools
	}
	return nil
}

type MCPToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson []byte                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPToolCallRequest) Reset() {
	*x = MCPToolCallRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPToolCallRequest) ProtoMessage() {}

func (x *MCPToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPToolCallRequest.ProtoReflect.Descriptor instead.
func (*MCPToolCallRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{24}
}

func (x *MCPToolCallRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPToolCallRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

type MCPToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPToolCallResponse) Reset() {
	*x = MCPToolCallResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPToolCallResponse) ProtoMessage() {}

func (x *MCPToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPToolCallResponse.ProtoReflect.Descriptor instead.
func (*MCPToolCallResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{25}
}

func (x *MCPToolCallResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *MCPToolCallResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *MCPToolCallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TypeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	SourcePath    string                 `protobuf:"bytes,5,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	SchemaRef     string                 `protobuf:"bytes,6,opt,name=schema_ref,json=schemaRef,proto3" json:"schema_ref,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeSummary) Reset() {
	*x = TypeSummary{}
	mi := &file_trove_v1_module_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeSummary) ProtoMessage() {}

func (x *TypeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeSummary.ProtoReflect.Descriptor instead.
func (*TypeSummary) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{26}
}

func (x *TypeSummary) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TypeSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TypeSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TypeSummary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TypeSummary) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *TypeSummary) GetSchemaRef() string {
	if x != nil {
		return x.SchemaRef
	}
	return ""
}

func (x *TypeSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceFilter  string                 `protobuf:"bytes,1,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesRequest) Reset() {
	*x = ListTypesRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesRequest) ProtoMessage() {}

func (x *ListTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTypesRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{27}
}

func (x *ListTypesRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

type ListTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*TypeSummary         `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesResponse) Reset() {
	*x = ListTypesResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesResponse) ProtoMessage() {}

func (x *ListTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTypesResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{28}
}

func (x *ListTypesResponse) GetTypes() []*TypeSummary {
	if x != nil {
		return x.Types
	}
	return nil
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{29}
}

func (x *GetTypeRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type GetTypeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        *TypeSummary           `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	DefinitionJson []byte                 `protobuf:"bytes,2,opt,name=definition_json,json=definitionJson,proto3" json:"definition_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTypeResponse) Reset() {
	*x = GetTypeResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeResponse) ProtoMessage() {}

func (x *GetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{30}
}

func (x *GetTypeResponse) GetSummary() *TypeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetTypeResponse) GetDefinitionJson() []byte {
	if x != nil {
		return x.DefinitionJson
	}
	return nil
}

type ExportTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTypeRequest) Reset() {
	*x = ExportTypeRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTypeRequest) ProtoMessage() {}

func (x *ExportTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTypeRequest.ProtoReflect.Descriptor instead.
func (*ExportTypeRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{31}
}

func (x *ExportTypeRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ExportTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtdJson       []byte                 `protobuf:"bytes,1,opt,name=ttd_json,json=ttdJson,proto3" json:"ttd_json,omitempty"`
	SchemaRef     string                 `protobuf:"bytes,2,opt,name=schema_ref,json=schemaRef,proto3" json:"schema_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTypeResponse) Reset() {
	*x = ExportTypeResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTypeResponse) ProtoMessage() {}

func (x *ExportTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTypeResponse.ProtoReflect.Descriptor instead.
func (*ExportTypeResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{32}
}

func (x *ExportTypeResponse) GetTtdJson() []byte {
	if x != nil {
		return x.TtdJson
	}
	return nil
}

func (x *ExportTypeResponse) GetSchemaRef() string {
	if x != nil {
		return x.SchemaRef
	}
	return ""
}

type ValidateTypeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtdJson       []byte                 `protobuf:"bytes,1,opt,name=ttd_json,json=ttdJson,proto3" json:"ttd_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTypeDefinitionRequest) Reset() {
	*x = ValidateTypeDefinitionRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTypeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTypeDefinitionRequest) ProtoMessage() {}

func (x *ValidateTypeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTypeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ValidateTypeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{33}
}

func (x *ValidateTypeDefinitionRequest) GetTtdJson() []byte {
	if x != nil {
		return x.TtdJson
	}
	return nil
}

type ValidateTypeDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTypeDefinitionResponse) Reset() {
	*x = ValidateTypeDefinitionResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTypeDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTypeDefinitionResponse) ProtoMessage() {}

func (x *ValidateTypeDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTypeDefinitionResponse.ProtoReflect.Descriptor instead.
func (*ValidateTypeDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{34}
}

func (x *ValidateTypeDefinitionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTypeDefinitionResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ValidateTypeDefinitionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CLICommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLICommandRequest) Reset() {
	*x = CLICommandRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLICommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLICommandRequest) ProtoMessage() {}

func (x *CLICommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLICommandRequest.ProtoReflect.Descriptor instead.
func (*CLICommandRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{35}
}

func (x *CLICommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CLICommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CLICommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLICommandResponse) Reset() {
	*x = CLICommandResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLICommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLICommandResponse) ProtoMessage() {}

func (x *CLICommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLICommandResponse.ProtoReflect.Descriptor instead.
func (*CLICommandResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{36}
}

func (x *CLICommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CLICommandResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *CLICommandResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal plugin wire format: parent-process handle for CoreServices.
	// Module authors use trovemodule.Core instead.
	ServicesBrokerId uint32 `protobuf:"varint,1,opt,name=services_broker_id,json=servicesBrokerId,proto3" json:"services_broker_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{37}
}

func (x *RunRequest) GetServicesBrokerId() uint32 {
	if x != nil {
		return x.ServicesBrokerId
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{38}
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{39}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{40}
}

func (x *HealthcheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthcheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DispatchContext carries routing metadata for revision processors and sinks.
// It is not persisted in the journal.
type DispatchContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	Seen          []string               `protobuf:"bytes,2,rep,name=seen,proto3" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchContext) Reset() {
	*x = DispatchContext{}
	mi := &file_trove_v1_module_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchContext) ProtoMessage() {}

func (x *DispatchContext) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchContext.ProtoReflect.Descriptor instead.
func (*DispatchContext) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{41}
}

func (x *DispatchContext) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *DispatchContext) GetSeen() []string {
	if x != nil {
		return x.Seen
	}
	return nil
}

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *Revision              `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Context       *DispatchContext       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{42}
}

func (x *ProcessRequest) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *ProcessRequest) GetContext() *DispatchContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*Revision            `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{43}
}

func (x *ProcessResponse) GetRevisions() []*Revision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *Revision              `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Context       *DispatchContext       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_trove_v1_module_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{44}
}

func (x *HandleRequest) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *HandleRequest) GetContext() *DispatchContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_trove_v1_module_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trove_v1_module_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_trove_v1_module_proto_rawDescGZIP(), []int{45}
}

var File_trove_v1_module_proto protoreflect.FileDescriptor

const file_trove_v1_module_proto_rawDesc = "" +
	"\n" +
	"\x15trove/v1/module.proto\x12\btrove.v1\"\xa7\x02\n" +
	"\bRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x19\n" +
	"\bblob_ref\x18\x06 \x01(\tR\ablobRef\x12\x1d\n" +
	"\n" +
	"schema_ref\x18\a \x01(\tR\tschemaRef\x12\x1c\n" +
	"\toperation\x18\b \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"record_ref\x18\t \x01(\tR\trecordRef\x12\x1e\n" +
	"\n" +
	"transforms\x18\n" +
	" \x01(\fR\n" +
	"transforms\x12\x1a\n" +
	"\bproducer\x18\v \x01(\tR\bproducer\"\xe9\x01\n" +
	"\x15AppendRevisionRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x02 \x01(\tR\trecordRef\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1e\n" +
	"\n" +
	"transforms\x18\a \x01(\fR\n" +
	"transforms\x12\x19\n" +
	"\bblob_ref\x18\b \x01(\tR\ablobRef\"\xb4\x01\n" +
	"\x16AppendRevisionResponse\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x02 \x01(\tR\trecordRef\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\"\n" +
	"\fcompleteness\x18\x04 \x01(\tR\fcompleteness\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\"$\n" +
	"\x0eBlobPutRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\",\n" +
	"\x0fBlobPutResponse\x12\x19\n" +
	"\bblob_ref\x18\x01 \x01(\tR\ablobRef\"$\n" +
	"\x12GetRevisionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9d\x01\n" +
	"\x16SearchRevisionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vtype_prefix\x18\x02 \x01(\tR\n" +
	"typePrefix\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1b\n" +
	"\ttime_from\x18\x04 \x01(\tR\btimeFrom\x12\x17\n" +
	"\atime_to\x18\x05 \x01(\tR\x06timeTo\"K\n" +
	"\x17SearchRevisionsResponse\x120\n" +
	"\trevisions\x18\x01 \x03(\v2\x12.trove.v1.RevisionR\trevisions\"e\n" +
	"\x19GetRevisionsByTypeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\ttime_from\x18\x02 \x01(\tR\btimeFrom\x12\x17\n" +
	"\atime_to\x18\x03 \x01(\tR\x06timeTo\"\xe5\x01\n" +
	"\x06Record\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x01 \x01(\tR\trecordRef\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\"\n" +
	"\fcompleteness\x18\x03 \x01(\tR\fcompleteness\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x1f\n" +
	"\vcontent_ref\x18\a \x01(\tR\n" +
	"contentRef\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"K\n" +
	"\x10GetRecordRequest\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x01 \x01(\tR\trecordRef\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\xc4\x01\n" +
	"\x14SearchRecordsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vtype_prefix\x18\x02 \x01(\tR\n" +
	"typePrefix\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1b\n" +
	"\ttime_from\x18\x04 \x01(\tR\btimeFrom\x12\x17\n" +
	"\atime_to\x18\x05 \x01(\tR\x06timeTo\x12'\n" +
	"\x0finclude_deleted\x18\x06 \x01(\bR\x0eincludeDeleted\"C\n" +
	"\x15SearchRecordsResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.trove.v1.RecordR\arecords\"L\n" +
	"\x1cListIncompleteRecordsRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"K\n" +
	"\x1dListIncompleteRecordsResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.trove.v1.RecordR\arecords\"M\n" +
	"\x15SummarizeRangeRequest\x12\x1b\n" +
	"\ttime_from\x18\x01 \x01(\tR\btimeFrom\x12\x17\n" +
	"\atime_to\x18\x02 \x01(\tR\x06timeTo\"\xf6\x01\n" +
	"\aSummary\x12\x1b\n" +
	"\ttime_from\x18\x01 \x01(\tR\btimeFrom\x12\x17\n" +
	"\atime_to\x18\x02 \x01(\tR\x06timeTo\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x126\n" +
	"\aby_type\x18\x04 \x03(\v2\x1d.trove.v1.Summary.ByTypeEntryR\x06byType\x12,\n" +
	"\anotable\x18\x05 \x03(\v2\x12.trove.v1.RevisionR\anotable\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf7\x02\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0fmatched_pattern\x18\x03 \x01(\tR\x0ematchedPattern\x12F\n" +
	"\vpath_values\x18\x04 \x03(\v2%.trove.v1.HTTPRequest.PathValuesEntryR\n" +
	"pathValues\x12<\n" +
	"\aheaders\x18\x05 \x03(\v2\".trove.v1.HTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a=\n" +
	"\x0fPathValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\fHTTPResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12=\n" +
	"\aheaders\x18\x02 \x03(\v2#.trove.v1.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x03\n" +
	"\vAuthRequest\x12!\n" +
	"\fvalidator_id\x18\x01 \x01(\tR\vvalidatorId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12'\n" +
	"\x0fmatched_pattern\x18\x04 \x01(\tR\x0ematchedPattern\x12F\n" +
	"\vpath_values\x18\x05 \x03(\v2%.trove.v1.AuthRequest.PathValuesEntryR\n" +
	"pathValues\x12<\n" +
	"\aheaders\x18\x06 \x03(\v2\".trove.v1.AuthRequest.HeadersEntryR\aheaders\x12!\n" +
	"\froute_module\x18\a \x01(\tR\vrouteModule\x1a=\n" +
	"\x0fPathValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\aheaders\x18\x04 \x03(\v2#.trove.v1.AuthResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x11MCPToolDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\"\x15\n" +
	"\x13ListMCPToolsRequest\"I\n" +
	"\x14ListMCPToolsResponse\x121\n" +
	"\x05tools\x18\x01 \x03(\v2\x1b.trove.v1.MCPToolDescriptorR\x05tools\"O\n" +
	"\x12MCPToolCallRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\fR\rargumentsJson\"k\n" +
	"\x13MCPToolCallResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc7\x01\n" +
	"\vTypeSummary\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_path\x18\x05 \x01(\tR\n" +
	"sourcePath\x12\x1d\n" +
	"\n" +
	"schema_ref\x18\x06 \x01(\tR\tschemaRef\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"7\n" +
	"\x10ListTypesRequest\x12#\n" +
	"\rsource_filter\x18\x01 \x01(\tR\fsourceFilter\"@\n" +
	"\x11ListTypesResponse\x12+\n" +
	"\x05types\x18\x01 \x03(\v2\x15.trove.v1.TypeSummaryR\x05types\"\"\n" +
	"\x0eGetTypeRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"k\n" +
	"\x0fGetTypeResponse\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.trove.v1.TypeSummaryR\asummary\x12'\n" +
	"\x0fdefinition_json\x18\x02 \x01(\fR\x0edefinitionJson\"%\n" +
	"\x11ExportTypeRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"N\n" +
	"\x12ExportTypeResponse\x12\x19\n" +
	"\bttd_json\x18\x01 \x01(\fR\attdJson\x12\x1d\n" +
	"\n" +
	"schema_ref\x18\x02 \x01(\tR\tschemaRef\":\n" +
	"\x1dValidateTypeDefinitionRequest\x12\x19\n" +
	"\bttd_json\x18\x01 \x01(\fR\attdJson\"^\n" +
	"\x1eValidateTypeDefinitionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"A\n" +
	"\x11CLICommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"a\n" +
	"\x12CLICommandResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\":\n" +
	"\n" +
	"RunRequest\x12,\n" +
	"\x12services_broker_id\x18\x01 \x01(\rR\x10servicesBrokerId\"\r\n" +
	"\vRunResponse\"\x14\n" +
	"\x12HealthcheckRequest\"?\n" +
	"\x13HealthcheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x0fDispatchContext\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12\x12\n" +
	"\x04seen\x18\x02 \x03(\tR\x04seen\"u\n" +
	"\x0eProcessRequest\x12.\n" +
	"\brevision\x18\x01 \x01(\v2\x12.trove.v1.RevisionR\brevision\x123\n" +
	"\acontext\x18\x02 \x01(\v2\x19.trove.v1.DispatchContextR\acontext\"C\n" +
	"\x0fProcessResponse\x120\n" +
	"\trevisions\x18\x01 \x03(\v2\x12.trove.v1.RevisionR\trevisions\"t\n" +
	"\rHandleRequest\x12.\n" +
	"\brevision\x18\x01 \x01(\v2\x12.trove.v1.RevisionR\brevision\x123\n" +
	"\acontext\x18\x02 \x01(\v2\x19.trove.v1.DispatchContextR\acontext\"\x10\n" +
	"\x0eHandleResponse2\xae\t\n" +
	"\fCoreServices\x12S\n" +
	"\x0eAppendRevision\x12\x1f.trove.v1.AppendRevisionRequest\x1a .trove.v1.AppendRevisionResponse\x12>\n" +
	"\aBlobPut\x12\x18.trove.v1.BlobPutRequest\x1a\x19.trove.v1.BlobPutResponse\x12?\n" +
	"\vGetRevision\x12\x1c.trove.v1.GetRevisionRequest\x1a\x12.trove.v1.Revision\x12V\n" +
	"\x0fSearchRevisions\x12 .trove.v1.SearchRevisionsRequest\x1a!.trove.v1.SearchRevisionsResponse\x12\\\n" +
	"\x12GetRevisionsByType\x12#.trove.v1.GetRevisionsByTypeRequest\x1a!.trove.v1.SearchRevisionsResponse\x129\n" +
	"\tGetRecord\x12\x1a.trove.v1.GetRecordRequest\x1a\x10.trove.v1.Record\x12P\n" +
	"\rSearchRecords\x12\x1e.trove.v1.SearchRecordsRequest\x1a\x1f.trove.v1.SearchRecordsResponse\x12h\n" +
	"\x15ListIncompleteRecords\x12&.trove.v1.ListIncompleteRecordsRequest\x1a'.trove.v1.ListIncompleteRecordsResponse\x12D\n" +
	"\x0eSummarizeRange\x12\x1f.trove.v1.SummarizeRangeRequest\x1a\x11.trove.v1.Summary\x12M\n" +
	"\fListMCPTools\x12\x1d.trove.v1.ListMCPToolsRequest\x1a\x1e.trove.v1.ListMCPToolsResponse\x12J\n" +
	"\vCallMCPTool\x12\x1c.trove.v1.MCPToolCallRequest\x1a\x1d.trove.v1.MCPToolCallResponse\x12D\n" +
	"\tListTypes\x12\x1a.trove.v1.ListTypesRequest\x1a\x1b.trove.v1.ListTypesResponse\x12>\n" +
	"\aGetType\x12\x18.trove.v1.GetTypeRequest\x1a\x19.trove.v1.GetTypeResponse\x12G\n" +
	"\n" +
	"ExportType\x12\x1b.trove.v1.ExportTypeRequest\x1a\x1c.trove.v1.ExportTypeResponse\x12k\n" +
	"\x16ValidateTypeDefinition\x12'.trove.v1.ValidateTypeDefinitionRequest\x1a(.trove.v1.ValidateTypeDefinitionResponse2I\n" +
	"\n" +
	"HTTPModule\x12;\n" +
	"\n" +
	"HandleHTTP\x12\x15.trove.v1.HTTPRequest\x1a\x16.trove.v1.HTTPResponse2K\n" +
	"\n" +
	"AuthModule\x12=\n" +
	"\fValidateAuth\x12\x15.trove.v1.AuthRequest\x1a\x16.trove.v1.AuthResponse2T\n" +
	"\tMCPModule\x12G\n" +
	"\bCallTool\x12\x1c.trove.v1.MCPToolCallRequest\x1a\x1d.trove.v1.MCPToolCallResponse2T\n" +
	"\tCLIModule\x12G\n" +
	"\n" +
	"RunCommand\x12\x1b.trove.v1.CLICommandRequest\x1a\x1c.trove.v1.CLICommandResponse2\x8e\x01\n" +
	"\fSourceModule\x122\n" +
	"\x03Run\x12\x14.trove.v1.RunRequest\x1a\x15.trove.v1.RunResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.trove.v1.HealthcheckRequest\x1a\x1d.trove.v1.HealthcheckResponse2\x9d\x01\n" +
	"\x0fProcessorModule\x12>\n" +
	"\aProcess\x12\x18.trove.v1.ProcessRequest\x1a\x19.trove.v1.ProcessResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.trove.v1.HealthcheckRequest\x1a\x1d.trove.v1.HealthcheckResponse2\x95\x01\n" +
	"\n" +
	"SinkModule\x12;\n" +
	"\x06Handle\x12\x17.trove.v1.HandleRequest\x1a\x18.trove.v1.HandleResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.trove.v1.HealthcheckRequest\x1a\x1d.trove.v1.HealthcheckResponseB=Z;github.com/joshmcarthur/trove/internal/modules/rpc;troverpcb\x06proto3"

var (
	file_trove_v1_module_proto_rawDescOnce sync.Once
	file_trove_v1_module_proto_rawDescData []byte
)

func file_trove_v1_module_proto_rawDescGZIP() []byte {
	file_trove_v1_module_proto_rawDescOnce.Do(func() {
		file_trove_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trove_v1_module_proto_rawDesc), len(file_trove_v1_module_proto_rawDesc)))
	})
	return file_trove_v1_module_proto_rawDescData
}

var file_trove_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 53)
var file_trove_v1_module_proto_goTypes = []any{
	(*Revision)(nil),                       // 0: trove.v1.Revision
	(*AppendRevisionRequest)(nil),          // 1: trove.v1.AppendRevisionRequest
	(*AppendRevisionResponse)(nil),         // 2: trove.v1.AppendRevisionResponse
	(*BlobPutRequest)(nil),                 // 3: trove.v1.BlobPutRequest
	(*BlobPutResponse)(nil),                // 4: trove.v1.BlobPutResponse
	(*GetRevisionRequest)(nil),             // 5: trove.v1.GetRevisionRequest
	(*SearchRevisionsRequest)(nil),         // 6: trove.v1.SearchRevisionsRequest
	(*SearchRevisionsResponse)(nil),        // 7: trove.v1.SearchRevisionsResponse
	(*GetRevisionsByTypeRequest)(nil),      // 8: trove.v1.GetRevisionsByTypeRequest
	(*Record)(nil),                         // 9: trove.v1.Record
	(*GetRecordRequest)(nil),               // 10: trove.v1.GetRecordRequest
	(*SearchRecordsRequest)(nil),           // 11: trove.v1.SearchRecordsRequest
	(*SearchRecordsResponse)(nil),          // 12: trove.v1.SearchRecordsResponse
	(*ListIncompleteRecordsRequest)(nil),   // 13: trove.v1.ListIncompleteRecordsRequest
	(*ListIncompleteRecordsResponse)(nil),  // 14: trove.v1.ListIncompleteRecordsResponse
	(*SummarizeRangeRequest)(nil),          // 15: trove.v1.SummarizeRangeRequest
	(*Summary)(nil),                        // 16: trove.v1.Summary
	(*HTTPRequest)(nil),                    // 17: trove.v1.HTTPRequest
	(*HTTPResponse)(nil),                   // 18: trove.v1.HTTPResponse
	(*AuthRequest)(nil),                    // 19: trove.v1.AuthRequest
	(*AuthResponse)(nil),                   // 20: trove.v1.AuthResponse
	(*MCPToolDescriptor)(nil),              // 21: trove.v1.MCPToolDescriptor
	(*ListMCPToolsRequest)(nil),            // 22: trove.v1.ListMCPToolsRequest
	(*ListMCPToolsResponse)(nil),           // 23: trove.v1.ListMCPToolsResponse
	(*MCPToolCallRequest)(nil),             // 24: trove.v1.MCPToolCallRequest
	(*MCPToolCallResponse)(nil),            // 25: trove.v1.MCPToolCallResponse
	(*TypeSummary)(nil),                    // 26: trove.v1.TypeSummary
	(*ListTypesRequest)(nil),               // 27: trove.v1.ListTypesRequest
	(*ListTypesResponse)(nil),              // 28: trove.v1.ListTypesResponse
	(*GetTypeRequest)(nil),                 // 29: trove.v1.GetTypeRequest
	(*GetTypeResponse)(nil),                // 30: trove.v1.GetTypeResponse
	(*ExportTypeRequest)(nil),              // 31: trove.v1.ExportTypeRequest
	(*ExportTypeResponse)(nil),             // 32: trove.v1.ExportTypeResponse
	(*ValidateTypeDefinitionRequest)(nil),  // 33: trove.v1.ValidateTypeDefinitionRequest
	(*ValidateTypeDefinitionResponse)(nil), // 34: trove.v1.ValidateTypeDefinitionResponse
	(*CLICommandRequest)(nil),              // 35: trove.v1.CLICommandRequest
	(*CLICommandResponse)(nil),             // 36: trove.v1.CLICommandResponse
	(*RunRequest)(nil),                     // 37: trove.v1.RunRequest
	(*RunResponse)(nil),                    // 38: trove.v1.RunResponse
	(*HealthcheckRequest)(nil),             // 39: trove.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil),            // 40: trove.v1.HealthcheckResponse
	(*DispatchContext)(nil),                // 41: trove.v1.DispatchContext
	(*ProcessRequest)(nil),                 // 42: trove.v1.ProcessRequest
	(*ProcessResponse)(nil),                // 43: trove.v1.ProcessResponse
	(*HandleRequest)(nil),                  // 44: trove.v1.HandleRequest
	(*HandleResponse)(nil),                 // 45: trove.v1.HandleResponse
	nil,                                    // 46: trove.v1.Summary.ByTypeEntry
	nil,                                    // 47: trove.v1.HTTPRequest.PathValuesEntry
	nil,                                    // 48: trove.v1.HTTPRequest.HeadersEntry
	nil,                                    // 49: trove.v1.HTTPResponse.HeadersEntry
	nil,                                    // 50: trove.v1.AuthRequest.PathValuesEntry
	nil,                                    // 51: trove.v1.AuthRequest.HeadersEntry
	nil,                                    // 52: trove.v1.AuthResponse.HeadersEntry
}
var file_trove_v1_module_proto_depIdxs = []int32{
	0,  // 0: trove.v1.SearchRevisionsResponse.revisions:type_name -> trove.v1.Revision
	9,  // 1: trove.v1.SearchRecordsResponse.records:type_name -> trove.v1.Record
	9,  // 2: trove.v1.ListIncompleteRecordsResponse.records:type_name -> trove.v1.Record
	46, // 3: trove.v1.Summary.by_type:type_name -> trove.v1.Summary.ByTypeEntry
	0,  // 4: trove.v1.Summary.notable:type_name -> trove.v1.Revision
	47, // 5: trove.v1.HTTPRequest.path_values:type_name -> trove.v1.HTTPRequest.PathValuesEntry
	48, // 6: trove.v1.HTTPRequest.headers:type_name -> trove.v1.HTTPRequest.HeadersEntry
	49, // 7: trove.v1.HTTPResponse.headers:type_name -> trove.v1.HTTPResponse.HeadersEntry
	50, // 8: trove.v1.AuthRequest.path_values:type_name -> trove.v1.AuthRequest.PathValuesEntry
	51, // 9: trove.v1.AuthRequest.headers:type_name -> trove.v1.AuthRequest.HeadersEntry
	52, // 10: trove.v1.AuthResponse.headers:type_name -> trove.v1.AuthResponse.HeadersEntry
	21, // 11: trove.v1.ListMCPToolsResponse.tools:type_name -> trove.v1.MCPToolDescriptor
	26, // 12: trove.v1.ListTypesResponse.types:type_name -> trove.v1.TypeSummary
	26, // 13: trove.v1.GetTypeResponse.summary:type_name -> trove.v1.TypeSummary
	0,  // 14: trove.v1.ProcessRequest.revision:type_name -> trove.v1.Revision
	41, // 15: trove.v1.ProcessRequest.context:type_name -> trove.v1.DispatchContext
	0,  // 16: trove.v1.ProcessResponse.revisions:type_name -> trove.v1.Revision
	0,  // 17: trove.v1.HandleRequest.revision:type_name -> trove.v1.Revision
	41, // 18: trove.v1.HandleRequest.context:type_name -> trove.v1.DispatchContext
	1,  // 19: trove.v1.CoreServices.AppendRevision:input_type -> trove.v1.AppendRevisionRequest
	3,  // 20: trove.v1.CoreServices.BlobPut:input_type -> trove.v1.BlobPutRequest
	5,  // 21: trove.v1.CoreServices.GetRevision:input_type -> trove.v1.GetRevisionRequest
	6,  // 22: trove.v1.CoreServices.SearchRevisions:input_type -> trove.v1.SearchRevisionsRequest
	8,  // 23: trove.v1.CoreServices.GetRevisionsByType:input_type -> trove.v1.GetRevisionsByTypeRequest
	10, // 24: trove.v1.CoreServices.GetRecord:input_type -> trove.v1.GetRecordRequest
	11, // 25: trove.v1.CoreServices.SearchRecords:input_type -> trove.v1.SearchRecordsRequest
	13, // 26: trove.v1.CoreServices.ListIncompleteRecords:input_type -> trove.v1.ListIncompleteRecordsRequest
	15, // 27: trove.v1.CoreServices.SummarizeRange:input_type -> trove.v1.SummarizeRangeRequest
	22, // 28: trove.v1.CoreServices.ListMCPTools:input_type -> trove.v1.ListMCPToolsRequest
	24, // 29: trove.v1.CoreServices.CallMCPTool:input_type -> trove.v1.MCPToolCallRequest
	27, // 30: trove.v1.CoreServices.ListTypes:input_type -> trove.v1.ListTypesRequest
	29, // 31: trove.v1.CoreServices.GetType:input_type -> trove.v1.GetTypeRequest
	31, // 32: trove.v1.CoreServices.ExportType:input_type -> trove.v1.ExportTypeRequest
	33, // 33: trove.v1.CoreServices.ValidateTypeDefinition:input_type -> trove.v1.ValidateTypeDefinitionRequest
	17, // 34: trove.v1.HTTPModule.HandleHTTP:input_type -> trove.v1.HTTPRequest
	19, // 35: trove.v1.AuthModule.ValidateAuth:input_type -> trove.v1.AuthRequest
	24, // 36: trove.v1.MCPModule.CallTool:input_type -> trove.v1.MCPToolCallRequest
	35, // 37: trove.v1.CLIModule.RunCommand:input_type -> trove.v1.CLICommandRequest
	37, // 38: trove.v1.SourceModule.Run:input_type -> trove.v1.RunRequest
	39, // 39: trove.v1.SourceModule.Healthcheck:input_type -> trove.v1.HealthcheckRequest
	42, // 40: trove.v1.ProcessorModule.Process:input_type -> trove.v1.ProcessRequest
	39, // 41: trove.v1.ProcessorModule.Healthcheck:input_type -> trove.v1.HealthcheckRequest
	44, // 42: trove.v1.SinkModule.Handle:input_type -> trove.v1.HandleRequest
	39, // 43: trove.v1.SinkModule.Healthcheck:input_type -> trove.v1.HealthcheckRequest
	2,  // 44: trove.v1.CoreServices.AppendRevision:output_type -> trove.v1.AppendRevisionResponse
	4,  // 45: trove.v1.CoreServices.BlobPut:output_type -> trove.v1.BlobPutResponse
	0,  // 46: trove.v1.CoreServices.GetRevision:output_type -> trove.v1.Revision
	7,  // 47: trove.v1.CoreServices.SearchRevisions:output_type -> trove.v1.SearchRevisionsResponse
	7,  // 48: trove.v1.CoreServices.GetRevisionsByType:output_type -> trove.v1.SearchRevisionsResponse
	9,  // 49: trove.v1.CoreServices.GetRecord:output_type -> trove.v1.Record
	12, // 50: trove.v1.CoreServices.SearchRecords:output_type -> trove.v1.SearchRecordsResponse
	14, // 51: trove.v1.CoreServices.ListIncompleteRecords:output_type -> trove.v1.ListIncompleteRecordsResponse
	16, // 52: trove.v1.CoreServices.SummarizeRange:output_type -> trove.v1.Summary
	23, // 53: trove.v1.CoreServices.ListMCPTools:output_type -> trove.v1.ListMCPToolsResponse
	25, // 54: trove.v1.CoreServices.CallMCPTool:output_type -> trove.v1.MCPToolCallResponse
	28, // 55: trove.v1.CoreServices.ListTypes:output_type -> trove.v1.ListTypesResponse
	30, // 56: trove.v1.CoreServices.GetType:output_type -> trove.v1.GetTypeResponse
	32, // 57: trove.v1.CoreServices.ExportType:output_type -> trove.v1.ExportTypeResponse
	34, // 58: trove.v1.CoreServices.ValidateTypeDefinition:output_type -> trove.v1.ValidateTypeDefinitionResponse
	18, // 59: trove.v1.HTTPModule.HandleHTTP:output_type -> trove.v1.HTTPResponse
	20, // 60: trove.v1.AuthModule.ValidateAuth:output_type -> trove.v1.AuthResponse
	25, // 61: trove.v1.MCPModule.CallTool:output_type -> trove.v1.MCPToolCallResponse
	36, // 62: trove.v1.CLIModule.RunCommand:output_type -> trove.v1.CLICommandResponse
	38, // 63: trove.v1.SourceModule.Run:output_type -> trove.v1.RunResponse
	40, // 64: trove.v1.SourceModule.Healthcheck:output_type -> trove.v1.HealthcheckResponse
	43, // 65: trove.v1.ProcessorModule.Process:output_type -> trove.v1.ProcessResponse
	40, // 66: trove.v1.ProcessorModule.Healthcheck:output_type -> trove.v1.HealthcheckResponse
	45, // 67: trove.v1.SinkModule.Handle:output_type -> trove.v1.HandleResponse
	40, // 68: trove.v1.SinkModule.Healthcheck:output_type -> trove.v1.HealthcheckResponse
	44, // [44:69] is the sub-list for method output_type
	19, // [19:44] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_trove_v1_module_proto_init() }
func file_trove_v1_module_proto_init() {
	if File_trove_v1_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trove_v1_module_proto_rawDesc), len(file_trove_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   53,
			NumExtensions: 0,
			NumServices:   8,
		},
		GoTypes:           file_trove_v1_module_proto_goTypes,
		DependencyIndexes: file_trove_v1_module_proto_depIdxs,
		MessageInfos:      file_trove_v1_module_proto_msgTypes,
	}.Build()
	File_trove_v1_module_proto = out.File
	file_trove_v1_module_proto_goTypes = nil
	file_trove_v1_module_proto_depIdxs = nil
}
