// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: trove/v1/module.proto

package troverpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Source_Emit_FullMethodName = "/trove.v1.Source/Emit"
)

// SourceClient is the client API for Source service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Source is implemented by the Trove core; modules call Emit to append events.
type SourceClient interface {
	Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error)
}

type sourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceClient(cc grpc.ClientConnInterface) SourceClient {
	return &sourceClient{cc}
}

func (c *sourceClient) Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, Source_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServer is the server API for Source service.
// All implementations must embed UnimplementedSourceServer
// for forward compatibility.
//
// Source is implemented by the Trove core; modules call Emit to append events.
type SourceServer interface {
	Emit(context.Context, *Event) (*EmitResponse, error)
	mustEmbedUnimplementedSourceServer()
}

// UnimplementedSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServer struct{}

func (UnimplementedSourceServer) Emit(context.Context, *Event) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedSourceServer) mustEmbedUnimplementedSourceServer() {}
func (UnimplementedSourceServer) testEmbeddedByValue()                {}

// UnsafeSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServer will
// result in compilation errors.
type UnsafeSourceServer interface {
	mustEmbedUnimplementedSourceServer()
}

func RegisterSourceServer(s grpc.ServiceRegistrar, srv SourceServer) {
	// If the following call panics, it indicates UnimplementedSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Source_ServiceDesc, srv)
}

func _Source_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Source_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServer).Emit(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// Source_ServiceDesc is the grpc.ServiceDesc for Source service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Source_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.Source",
	HandlerType: (*SourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _Source_Emit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	SourceModule_Run_FullMethodName = "/trove.v1.SourceModule/Run"
)

// SourceModuleClient is the client API for SourceModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type sourceModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceModuleClient(cc grpc.ClientConnInterface) SourceModuleClient {
	return &sourceModuleClient{cc}
}

func (c *sourceModuleClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, SourceModule_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceModuleServer is the server API for SourceModule service.
// All implementations must embed UnimplementedSourceModuleServer
// for forward compatibility.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	mustEmbedUnimplementedSourceModuleServer()
}

// UnimplementedSourceModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceModuleServer struct{}

func (UnimplementedSourceModuleServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedSourceModuleServer) mustEmbedUnimplementedSourceModuleServer() {}
func (UnimplementedSourceModuleServer) testEmbeddedByValue()                      {}

// UnsafeSourceModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceModuleServer will
// result in compilation errors.
type UnsafeSourceModuleServer interface {
	mustEmbedUnimplementedSourceModuleServer()
}

func RegisterSourceModuleServer(s grpc.ServiceRegistrar, srv SourceModuleServer) {
	// If the following call panics, it indicates UnimplementedSourceModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceModule_ServiceDesc, srv)
}

func _SourceModule_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceModuleServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceModule_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceModuleServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceModule_ServiceDesc is the grpc.ServiceDesc for SourceModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.SourceModule",
	HandlerType: (*SourceModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _SourceModule_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}
