// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: trove/v1/module.proto

package troverpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreServices_Emit_FullMethodName            = "/trove.v1.CoreServices/Emit"
	CoreServices_BlobPut_FullMethodName         = "/trove.v1.CoreServices/BlobPut"
	CoreServices_GetEvent_FullMethodName        = "/trove.v1.CoreServices/GetEvent"
	CoreServices_SearchEvents_FullMethodName    = "/trove.v1.CoreServices/SearchEvents"
	CoreServices_GetEventsByType_FullMethodName = "/trove.v1.CoreServices/GetEventsByType"
	CoreServices_SummarizeRange_FullMethodName  = "/trove.v1.CoreServices/SummarizeRange"
	CoreServices_ListMCPTools_FullMethodName    = "/trove.v1.CoreServices/ListMCPTools"
	CoreServices_CallMCPTool_FullMethodName     = "/trove.v1.CoreServices/CallMCPTool"
)

// CoreServicesClient is the client API for CoreServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreServices is implemented by the Trove parent process. Modules reach it
// through trovemodule.Core; see RunRequest.services_broker_id for the internal
// plugin wire format.
type CoreServicesClient interface {
	Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error)
	BlobPut(ctx context.Context, in *BlobPutRequest, opts ...grpc.CallOption) (*BlobPutResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error)
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	GetEventsByType(ctx context.Context, in *GetEventsByTypeRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	SummarizeRange(ctx context.Context, in *SummarizeRangeRequest, opts ...grpc.CallOption) (*Summary, error)
	ListMCPTools(ctx context.Context, in *ListMCPToolsRequest, opts ...grpc.CallOption) (*ListMCPToolsResponse, error)
	CallMCPTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error)
}

type coreServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServicesClient(cc grpc.ClientConnInterface) CoreServicesClient {
	return &coreServicesClient{cc}
}

func (c *coreServicesClient) Emit(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, CoreServices_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) BlobPut(ctx context.Context, in *BlobPutRequest, opts ...grpc.CallOption) (*BlobPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobPutResponse)
	err := c.cc.Invoke(ctx, CoreServices_BlobPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Event, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Event)
	err := c.cc.Invoke(ctx, CoreServices_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, CoreServices_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) GetEventsByType(ctx context.Context, in *GetEventsByTypeRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, CoreServices_GetEventsByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) SummarizeRange(ctx context.Context, in *SummarizeRangeRequest, opts ...grpc.CallOption) (*Summary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Summary)
	err := c.cc.Invoke(ctx, CoreServices_SummarizeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) ListMCPTools(ctx context.Context, in *ListMCPToolsRequest, opts ...grpc.CallOption) (*ListMCPToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMCPToolsResponse)
	err := c.cc.Invoke(ctx, CoreServices_ListMCPTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServicesClient) CallMCPTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPToolCallResponse)
	err := c.cc.Invoke(ctx, CoreServices_CallMCPTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServicesServer is the server API for CoreServices service.
// All implementations must embed UnimplementedCoreServicesServer
// for forward compatibility.
//
// CoreServices is implemented by the Trove parent process. Modules reach it
// through trovemodule.Core; see RunRequest.services_broker_id for the internal
// plugin wire format.
type CoreServicesServer interface {
	Emit(context.Context, *Event) (*EmitResponse, error)
	BlobPut(context.Context, *BlobPutRequest) (*BlobPutResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*Event, error)
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	GetEventsByType(context.Context, *GetEventsByTypeRequest) (*SearchEventsResponse, error)
	SummarizeRange(context.Context, *SummarizeRangeRequest) (*Summary, error)
	ListMCPTools(context.Context, *ListMCPToolsRequest) (*ListMCPToolsResponse, error)
	CallMCPTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error)
	mustEmbedUnimplementedCoreServicesServer()
}

// UnimplementedCoreServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServicesServer struct{}

func (UnimplementedCoreServicesServer) Emit(context.Context, *Event) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedCoreServicesServer) BlobPut(context.Context, *BlobPutRequest) (*BlobPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlobPut not implemented")
}
func (UnimplementedCoreServicesServer) GetEvent(context.Context, *GetEventRequest) (*Event, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedCoreServicesServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedCoreServicesServer) GetEventsByType(context.Context, *GetEventsByTypeRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByType not implemented")
}
func (UnimplementedCoreServicesServer) SummarizeRange(context.Context, *SummarizeRangeRequest) (*Summary, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeRange not implemented")
}
func (UnimplementedCoreServicesServer) ListMCPTools(context.Context, *ListMCPToolsRequest) (*ListMCPToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMCPTools not implemented")
}
func (UnimplementedCoreServicesServer) CallMCPTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallMCPTool not implemented")
}
func (UnimplementedCoreServicesServer) mustEmbedUnimplementedCoreServicesServer() {}
func (UnimplementedCoreServicesServer) testEmbeddedByValue()                      {}

// UnsafeCoreServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServicesServer will
// result in compilation errors.
type UnsafeCoreServicesServer interface {
	mustEmbedUnimplementedCoreServicesServer()
}

func RegisterCoreServicesServer(s grpc.ServiceRegistrar, srv CoreServicesServer) {
	// If the following call panics, it indicates UnimplementedCoreServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreServices_ServiceDesc, srv)
}

func _CoreServices_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).Emit(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_BlobPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).BlobPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_BlobPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).BlobPut(ctx, req.(*BlobPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_GetEventsByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).GetEventsByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_GetEventsByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).GetEventsByType(ctx, req.(*GetEventsByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_SummarizeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).SummarizeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_SummarizeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).SummarizeRange(ctx, req.(*SummarizeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_ListMCPTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMCPToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).ListMCPTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_ListMCPTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).ListMCPTools(ctx, req.(*ListMCPToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreServices_CallMCPTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServicesServer).CallMCPTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreServices_CallMCPTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServicesServer).CallMCPTool(ctx, req.(*MCPToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreServices_ServiceDesc is the grpc.ServiceDesc for CoreServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.CoreServices",
	HandlerType: (*CoreServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _CoreServices_Emit_Handler,
		},
		{
			MethodName: "BlobPut",
			Handler:    _CoreServices_BlobPut_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _CoreServices_GetEvent_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _CoreServices_SearchEvents_Handler,
		},
		{
			MethodName: "GetEventsByType",
			Handler:    _CoreServices_GetEventsByType_Handler,
		},
		{
			MethodName: "SummarizeRange",
			Handler:    _CoreServices_SummarizeRange_Handler,
		},
		{
			MethodName: "ListMCPTools",
			Handler:    _CoreServices_ListMCPTools_Handler,
		},
		{
			MethodName: "CallMCPTool",
			Handler:    _CoreServices_CallMCPTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	HTTPModule_HandleHTTP_FullMethodName = "/trove.v1.HTTPModule/HandleHTTP"
)

// HTTPModuleClient is the client API for HTTPModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTPModule is implemented by modules that handle HTTP routes via the gateway.
type HTTPModuleClient interface {
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type hTTPModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPModuleClient(cc grpc.ClientConnInterface) HTTPModuleClient {
	return &hTTPModuleClient{cc}
}

func (c *hTTPModuleClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, HTTPModule_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPModuleServer is the server API for HTTPModule service.
// All implementations must embed UnimplementedHTTPModuleServer
// for forward compatibility.
//
// HTTPModule is implemented by modules that handle HTTP routes via the gateway.
type HTTPModuleServer interface {
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	mustEmbedUnimplementedHTTPModuleServer()
}

// UnimplementedHTTPModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPModuleServer struct{}

func (UnimplementedHTTPModuleServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedHTTPModuleServer) mustEmbedUnimplementedHTTPModuleServer() {}
func (UnimplementedHTTPModuleServer) testEmbeddedByValue()                    {}

// UnsafeHTTPModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPModuleServer will
// result in compilation errors.
type UnsafeHTTPModuleServer interface {
	mustEmbedUnimplementedHTTPModuleServer()
}

func RegisterHTTPModuleServer(s grpc.ServiceRegistrar, srv HTTPModuleServer) {
	// If the following call panics, it indicates UnimplementedHTTPModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPModule_ServiceDesc, srv)
}

func _HTTPModule_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPModuleServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPModule_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPModuleServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPModule_ServiceDesc is the grpc.ServiceDesc for HTTPModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.HTTPModule",
	HandlerType: (*HTTPModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHTTP",
			Handler:    _HTTPModule_HandleHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	MCPModule_CallTool_FullMethodName = "/trove.v1.MCPModule/CallTool"
)

// MCPModuleClient is the client API for MCPModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPModule is implemented by modules that provide MCP tools.
type MCPModuleClient interface {
	CallTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error)
}

type mCPModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPModuleClient(cc grpc.ClientConnInterface) MCPModuleClient {
	return &mCPModuleClient{cc}
}

func (c *mCPModuleClient) CallTool(ctx context.Context, in *MCPToolCallRequest, opts ...grpc.CallOption) (*MCPToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MCPToolCallResponse)
	err := c.cc.Invoke(ctx, MCPModule_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPModuleServer is the server API for MCPModule service.
// All implementations must embed UnimplementedMCPModuleServer
// for forward compatibility.
//
// MCPModule is implemented by modules that provide MCP tools.
type MCPModuleServer interface {
	CallTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error)
	mustEmbedUnimplementedMCPModuleServer()
}

// UnimplementedMCPModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPModuleServer struct{}

func (UnimplementedMCPModuleServer) CallTool(context.Context, *MCPToolCallRequest) (*MCPToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMCPModuleServer) mustEmbedUnimplementedMCPModuleServer() {}
func (UnimplementedMCPModuleServer) testEmbeddedByValue()                   {}

// UnsafeMCPModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPModuleServer will
// result in compilation errors.
type UnsafeMCPModuleServer interface {
	mustEmbedUnimplementedMCPModuleServer()
}

func RegisterMCPModuleServer(s grpc.ServiceRegistrar, srv MCPModuleServer) {
	// If the following call panics, it indicates UnimplementedMCPModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPModule_ServiceDesc, srv)
}

func _MCPModule_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MCPToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPModuleServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPModule_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPModuleServer).CallTool(ctx, req.(*MCPToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPModule_ServiceDesc is the grpc.ServiceDesc for MCPModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.MCPModule",
	HandlerType: (*MCPModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTool",
			Handler:    _MCPModule_CallTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}

const (
	SourceModule_Run_FullMethodName         = "/trove.v1.SourceModule/Run"
	SourceModule_Healthcheck_FullMethodName = "/trove.v1.SourceModule/Healthcheck"
)

// SourceModuleClient is the client API for SourceModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type sourceModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceModuleClient(cc grpc.ClientConnInterface) SourceModuleClient {
	return &sourceModuleClient{cc}
}

func (c *sourceModuleClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, SourceModule_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceModuleClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, SourceModule_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceModuleServer is the server API for SourceModule service.
// All implementations must embed UnimplementedSourceModuleServer
// for forward compatibility.
//
// SourceModule is implemented by source modules; the core calls Run to start emission.
type SourceModuleServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	mustEmbedUnimplementedSourceModuleServer()
}

// UnimplementedSourceModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceModuleServer struct{}

func (UnimplementedSourceModuleServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedSourceModuleServer) Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedSourceModuleServer) mustEmbedUnimplementedSourceModuleServer() {}
func (UnimplementedSourceModuleServer) testEmbeddedByValue()                      {}

// UnsafeSourceModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceModuleServer will
// result in compilation errors.
type UnsafeSourceModuleServer interface {
	mustEmbedUnimplementedSourceModuleServer()
}

func RegisterSourceModuleServer(s grpc.ServiceRegistrar, srv SourceModuleServer) {
	// If the following call panics, it indicates UnimplementedSourceModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceModule_ServiceDesc, srv)
}

func _SourceModule_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceModuleServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceModule_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceModuleServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceModule_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceModuleServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceModule_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceModuleServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceModule_ServiceDesc is the grpc.ServiceDesc for SourceModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trove.v1.SourceModule",
	HandlerType: (*SourceModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _SourceModule_Run_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _SourceModule_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trove/v1/module.proto",
}
